import Slide1Img1 from "../../assets/Slide1Img1.png";

export const products = [
  {
    image: Slide1Img1,
    title: "The north coat",
    originalPrice: 360,
    discountPrice: 260,
    rate: 5,
    isNew: true,
    bestSelling: true,
  },
  {
    image: Slide1Img1,
    title: "The north coat",
    originalPrice: 360,
    discountPrice: 260,
    rate: 4,
    isNew: false,
    bestSelling: true,
    flash: -50,
  },
  {
    image: Slide1Img1,
    title: "The north coat",
    originalPrice: 360,
    discountPrice: 260,
    rate: 3,
    isNew: true,
    bestSelling: true,
    flash: -50,
  },
  {
    image: Slide1Img1,
    title: "The north coat",
    originalPrice: 360,
    discountPrice: 260,
    rate: 5,
    isNew: true,
    bestSelling: true,
    flash: -50,
  },
  {
    image: Slide1Img1,
    title: "The north coat",
    originalPrice: 360,
    discountPrice: 260,
    rate: 5,
    isNew: false,
    bestSelling: false,
  },
  {
    image: Slide1Img1,
    title: "The north coat",
    originalPrice: 360,
    discountPrice: 260,
    rate: 5,
    isNew: false,
    bestSelling: false,
  },
  {
    image: Slide1Img1,
    title: "The north coat",
    originalPrice: 360,
    discountPrice: 260,
    rate: 5,
    isNew: false,
    bestSelling: false,
  },
  {
    image: Slide1Img1,
    title: "The north coat",
    originalPrice: 360,
    discountPrice: 260,
    rate: 5,
    isNew: false,
    bestSelling: false,
  },
  {
    image: Slide1Img1,
    title: "Test Product",
    originalPrice: 360,
    discountPrice: 260,
    rate: 5,
    isNew: false,
    bestSelling: false,
    flash: -50,
  },
  {
    image: Slide1Img1,
    title: "Test Product",
    originalPrice: 360,
    discountPrice: 260,
    rate: 5,
    isNew: false,
    bestSelling: false,
  },
];
